apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-config
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "end-platform.labels" . | nindent 4 }}
data:
  LOGIN_TITLE: {{ .Values.ui.LOGIN_TITLE | quote }}
  REGISTER_TITLE: {{ .Values.ui.REGISTER_TITLE | quote }}
  WELCOME_MESSAGE: {{ .Values.ui.WELCOME_MESSAGE | quote }}
