{{- if .Values.cronjobs.notificationSender.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: notification-sender
  namespace: {{ .Values.namespace }}
  labels:
    app: notification-sender
    {{- include "end-platform.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.cronjobs.notificationSender.schedule | quote }}
  concurrencyPolicy: {{ .Values.cronjobs.notificationSender.concurrencyPolicy | default "Forbid" }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: notification-sender
            {{- include "end-platform.labels" . | nindent 12 }}
        spec:
          restartPolicy: OnFailure
          containers:
            - name: job
              image: "{{ .Values.images.jobs.repository }}:{{ .Values.images.jobs.tag }}"
              imagePullPolicy: {{ .Values.images.jobs.pullPolicy }}
              command: ["python", "notification_sender.py"]
              envFrom:
                - configMapRef: { name: app-config }
              env:
                - name: DB_USER
                  valueFrom: { secretKeyRef: { name: db-secret, key: DB_USER } }
                - name: DB_PASSWORD
                  valueFrom: { secretKeyRef: { name: db-secret, key: DB_PASSWORD } }
                - name: DB_NAME
                  valueFrom: { secretKeyRef: { name: db-secret, key: DB_NAME } }
{{- end }}
