apiVersion: v1
kind: Service
metadata:
  name: report-service
  namespace: {{ .Values.namespace }}
  labels:
    app: report-service
    {{- include "end-platform.labels" . | nindent 4 }}
spec:
  type: NodePort
  selector:
    app: report-service
  ports:
    - name: http
      port: 80
      targetPort: 8000
      nodePort: {{ .Values.service.nodePorts.report }}
