apiVersion: apps/v1
kind: Deployment
metadata:
  name: report-service
  namespace: {{ .Values.namespace }}
  labels:
    app: report-service
    {{- include "end-platform.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount.report }}
  selector:
    matchLabels:
      app: report-service
  template:
    metadata:
      labels:
        app: report-service
        {{- include "end-platform.labels" . | nindent 8 }}
    spec:
      containers:
        - name: report-service
          image: "{{ .Values.images.report.repository }}:{{ .Values.images.report.tag }}"
          imagePullPolicy: {{ .Values.images.report.pullPolicy }}
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef: { name: app-config }
          env:
            - name: DB_USER
              valueFrom: { secretKeyRef: { name: db-secret, key: DB_USER } }
            - name: DB_PASSWORD
              valueFrom: { secretKeyRef: { name: db-secret, key: DB_PASSWORD } }
            - name: DB_NAME
              valueFrom: { secretKeyRef: { name: db-secret, key: DB_NAME } }
          livenessProbe:
            httpGet: { path: /health/live, port: 8000 }
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet: { path: /health/ready, port: 8000 }
            initialDelaySeconds: 30
            periodSeconds: 10
