apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: end
  labels:
    app: user-platform
data:
  APP_NAME: "User Platform"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "usersdb"
