apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-config
  namespace: end
  labels:
    app: user-platform
data:
  LOGIN_TITLE: "Вход в систему"
  REGISTER_TITLE: "Регистрация"
  WELCOME_MESSAGE: "Добро пожаловать в платформу"
