apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: end
  labels:
    app: user-platform
type: Opaque
stringData:
  DB_USER: "user"
  DB_PASSWORD: "password"
  DB_NAME: "usersdb"
