apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: end
  labels:
    app: postgres
    tier: db
spec:
  type: ClusterIP
  selector:
    app: postgres
    tier: db
  ports:
    - name: pg
      port: 5432
      targetPort: 5432
