apiVersion: v1
kind: Service
metadata:
  name: profile-service
  namespace: end
  labels:
    app: profile-service
spec:
  type: NodePort
  selector:
    app: profile-service
    tier: backend
  ports:
    - name: http
      port: 80
      targetPort: 8000
      nodePort: 30081
