apiVersion: v1
kind: ConfigMap
metadata:
  name: ui-config
  namespace: {{ .Values.namespace | quote }}
  labels:
    {{- include "upe.labels" . | nindent 4 }}
    app.kubernetes.io/component: ui-config
data:
{{- range $k, $v := .Values.uiConfig }}
  {{ $k }}: {{ $v | quote }}
{{- end }}
