apiVersion: v1
kind: Secret
metadata:
  name: platform-secrets
  namespace: {{ .Values.namespace | quote }}
  labels:
    {{- include "upe.labels" . | nindent 4 }}
    app.kubernetes.io/component: secret
type: Opaque
stringData:
  DB_PASSWORD: {{ .Values.secrets.dbPassword | quote }}
  JWT_SECRET: {{ .Values.secrets.jwtSecret | quote }}
