apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: user-platform-exam
  labels:
    app.kubernetes.io/name: monolith-app
    app.kubernetes.io/part-of: user-platform
data:
  LOG_LEVEL: "INFO"
  JWT_ISSUER: "user-platform"
  LOGIN_TITLE: "Вход в систему"
  REGISTER_TITLE: "Регистрация"
  WELCOME_MESSAGE: "Добро пожаловать в платформу"
